FROM ubuntu:24.04
RUN apt-get update -qq && \
    apt-get install -y -qq --no-install-recommends \
        hping3 \
        slowhttptest \
        curl \
        tcpdump \
        iproute2 \
        iputils-ping \
    && rm -rf /var/lib/apt/lists/*
